#!/bin/sh

case "$1" in
   'start')
       if [ ! -d "/mnt/jumpstart" ]; then 

          echo "Running the script to nuke old data out of the audit."
	  if [ -f "/home/audit/scripts/audit_cleanout.pl" ]; then
             /home/audit/scripts/audit_cleanout.pl
	     /home/audit/scripts/hardware_push.pl
	     /home/audit/scripts/patchdiag_to_db.pl
	     /home/audit/scripts/pkginfo_push.pl
          else
             /root/cfengine/scripts/audit_cleanout.pl
          fi

          echo "Deleting this script from /etc/rc3.d"
          /bin/rm /etc/rc3.d/S99audit_scrub

       else 
          echo "/mnt/jumpstart still exists, not running cfengine script."
       fi
       ;;

	'stop')
	  echo "Tried to stop /etc/rc3.d/S99audit_scrub."
	  echo "This script doesn't -stop-."
          echo "So something broke."
          ;;
esac
